use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::client::{tools::ToolCallRequest, usage::TokenUsage};

/// The complete, non-streaming response from a completion call.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CompletionResponse {
    pub id: String,
    /// Provider-specific model identifier that generated the response.
    pub model: String,
    /// Opaque identifier assigned by the provider for this response.
    pub response_id: String,
    /// Ordered list of content blocks produced by the model.
    pub contents: Vec<CompletionResponseContent>,
    /// Token accounting for this response.
    pub usage: TokenUsage,
}

/// A single content block within a [`CompletionResponse`].
#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum CompletionResponseContent {
    /// Visible text generated by the model.
    Text(String),
    /// Internal chain-of-thought produced before the visible answer.
    Thought(String),
    /// A request from the model to invoke a tool.
    ToolCall(ToolCallRequest),
}

impl CompletionResponse {
    pub fn new(
        id: String,
        model: String,
        response_id: String,
        contents: Vec<CompletionResponseContent>,
        usage: TokenUsage,
    ) -> Self {
        Self {
            id,
            model,
            response_id,
            contents,
            usage,
        }
    }

    pub fn text(&self) -> Option<&str> {
        self.contents.iter().find_map(|c| match c {
            CompletionResponseContent::Text(val) => Some(val.as_str()),
            _ => None,
        })
    }

    pub fn text_or_default(&self) -> String {
        let content = self.contents.iter().find_map(|c| match c {
            CompletionResponseContent::Text(val) => Some(val.as_str()),
            _ => None,
        });
        content.unwrap_or_default().to_string()
    }
}

/// A single chunk delivered by a streaming completion call.
///
/// Chunks arrive incrementally as the model generates output. When `is_final`
/// is `true` the stream is finished and `usage` is populated with the full
/// token accounting for the request.
///
/// Use the constructor helpers ([`stop`](Self::stop), [`content`](Self::content),
/// [`thought`](Self::thought), [`tool_call`](Self::tool_call)) to build chunks
/// without manually zeroing unused fields.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct CompletionChunkResponse {
    pub id: String,
    /// Model that generated this chunk (only set on the final chunk).
    pub model: String,
    /// Provider-assigned response ID (only set on the final chunk).
    pub response_id: String,
    /// Incremental visible text for this chunk.
    pub content: String,
    /// Incremental thought / reasoning text for this chunk.
    pub thought: String,
    /// Raw extended-thinking text as returned by the provider.
    pub thinking: String,
    /// pipeline status — UI only, never stored in turns
    pub status: String,
    /// `true` on the last chunk of the stream.
    pub is_final: bool,
    /// Token usage populated on the final chunk; `None` for intermediate chunks.
    pub usage: Option<TokenUsage>,
    /// Set when the model requests a tool call in this chunk.
    pub tool_call: Option<ToolCallRequest>,
    /// Only set on the final chunk — contains the full assembled response
    /// including all iterations, tool calls, and usage for storage.
    pub completion: Option<CompletionResponse>,
}

impl CompletionChunkResponse {
    /// Build a terminal chunk that signals the end of the stream.
    pub fn stop(
        id: String,
        model: String,
        response_id: String,
        final_content: String,
        usage: Option<TokenUsage>,
    ) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id: id.clone(),
            model: model.clone(),
            response_id: response_id.clone(),
            is_final: true,
            usage: usage.clone(),
            completion: Some(CompletionResponse {
                id,
                model,
                response_id,
                contents: vec![CompletionResponseContent::Text(final_content)],
                usage: usage.unwrap_or_default(),
            }),
            ..Default::default()
        }
    }

    /// Build a chunk carrying incremental visible content and optional raw thinking text.
    pub fn content(id: String, content: String, thinking: String) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id,
            content,
            thinking,
            is_final: false,
            ..Default::default()
        }
    }

    /// Build a chunk carrying an incremental chain-of-thought fragment.
    pub fn thought(id: String, thought: String) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id,
            thought,
            is_final: false,
            ..Default::default()
        }
    }

    pub fn status(status: String) -> CompletionChunkResponse {
        CompletionChunkResponse {
            status,
            ..Default::default()
        }
    }

    /// Build a chunk representing a tool-call request from the model.
    ///
    /// # Panics
    ///
    /// Panics if any of `id`, `name`, or `arguments` is `None`.
    pub fn tool_call(
        id: String,
        tool_id: Option<String>,
        name: Option<String>,
        arguments: Option<Value>,
    ) -> CompletionChunkResponse {
        CompletionChunkResponse {
            id,
            is_final: false,
            tool_call: Some(ToolCallRequest {
                id: tool_id.unwrap(),
                name: name.unwrap(),
                arguments: arguments.unwrap(),
            }),
            ..Default::default()
        }
    }
}
