use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Total "Fresh" or "Standard" input tokens sent.
    pub input_tokens: i32,

    /// Tokens read from a cache (OpenAI's cached_tokens or Anthropic's cache_read).
    /// These are a subset of your total input context but usually billed cheaper.
    pub cached_read_tokens: i32,

    /// Tokens written to the prompt cache during this call (billed at write rate).
    pub cached_write_tokens: i32,

    /// Tokens used specifically for tool definitions or results overhead.
    pub tool_use_tokens: i32,

    /// Internal "thinking" tokens (OpenAI Reasoning / Gemini Thoughts).
    /// Note: These are almost always billed as 'Output' tokens.
    pub reasoning_tokens: i32,

    /// The visible text tokens generated by the model.
    pub output_tokens: i32,

    /// The grand total (Input + Output + Reasoning).
    pub total_tokens: i32,
}

impl std::ops::AddAssign for TokenUsage {
    fn add_assign(&mut self, rhs: Self) {
        self.input_tokens += rhs.input_tokens;
        self.cached_read_tokens += rhs.cached_read_tokens;
        self.cached_write_tokens += rhs.cached_write_tokens;
        self.tool_use_tokens += rhs.tool_use_tokens;
        self.reasoning_tokens += rhs.reasoning_tokens;
        self.output_tokens += rhs.output_tokens;
        self.total_tokens += rhs.total_tokens;
    }
}
